version: "3.7"
networks:
  api-app:
services:
 app:
  build:
    args:
      user: max
      uid: 1000
    context: ./
    dockerfile: Dockerfile
  image: app
  container_name: app-main
  restart: unless-stopped
  working_dir: /var/www/
  volumes:
    - ./:/var/www
  networks:
    - api-app

 db:
  image: mysql:5.7
  container_name: app-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: 'app'
    MYSQL_ROOT_PASSWORD: 'pass'
    MYSQL_PASSWORD: 'pass'
    MYSQL_USER: 'user'
    SERVICE_TAGS: dev
    SERVICE_NAME: mysql
  ports:
    - 35061:3306
  volumes:
    - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  networks:
    - api-app

 nginx:
  image: nginx:1.17-alpine
  container_name: app-nginx
  restart: unless-stopped
  ports:
    - 8005:80
  volumes:
    - ./:/var/www
    - ./docker-compose/nginx:/etc/nginx/conf.d
  networks:
    - api-app

 redis:
    image: "bitnami/redis:latest"

    command: redis-server --requirepass my-secret-password

    ports:
      - "6379:6379"

    volumes:
#      - ./docker-compose/redis-data:/var/lib/redis
      - ./docker-compose/redis-data:/usr/local/etc/redis
#        - ./docker-compose/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - api-app

