openapi: 3.0.3
info:
    title: Laravel
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://localhost:8005'
paths:
    /api/login:
        post:
            summary: 'Log in .'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
            security: []
    /api/register:
        post:
            summary: 'Registration .'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
            security: []
    /api/products:
        get:
            summary: 'Display a listing of the products.'
            description: 'This endpoint allows you to get all products'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                example:
                                    - { id: 1, name: 'Iphone 12', description: 'Apple cell phone', price: '199.00', slug: iphone-12, created_at: '2021-05-03T20:21:21.000000Z', updated_at: null }
                                    - { id: 2, name: 'Samsusn s9', description: 'Best phone from Samsung', price: '266.00', slug: samsung-s9, created_at: '2021-05-03T20:22:54.000000Z', updated_at: null }
                                    - { id: 3, name: Nokia, description: 'Nokia cell phone', price: '156.00', slug: nokia, created_at: '2021-05-03T20:22:49.000000Z', updated_at: '2021-05-03T20:22:50.000000Z' }
            tags:
                - Endpoints
            security: []
        post:
            summary: 'Store a newly created product in storage.'
            description: 'This endpoint lets you create a new item.'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
    '/api/products/{id}':
        get:
            summary: 'Display the specified product by id.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    id: 1
                                    name: 'Iphone 12'
                                    description: 'Apple cell phone'
                                    price: '199.00'
                                    slug: iphone-12
                                    created_at: '2021-05-03T20:21:21.000000Z'
                                    updated_at: null
                                properties:
                                    id: { type: integer, example: 1 }
                                    name: { type: string, example: 'Iphone 12' }
                                    description: { type: string, example: 'Apple cell phone' }
                                    price: { type: string, example: '199.00' }
                                    slug: { type: string, example: iphone-12 }
                                    created_at: { type: string, example: '2021-05-03T20:21:21.000000Z' }
                                    updated_at: { type: string, example: null }
            tags:
                - Endpoints
            security: []
        put:
            summary: 'Update the specified product in storage.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
        delete:
            summary: 'Delete product.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
        parameters:
            -
                in: path
                name: id
                description: ''
                example: tenetur
                required: true
                schema:
                    type: string
    '/api/products/search/{name}':
        get:
            summary: 'Search for products by name.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                example:
                                    - { id: 1, name: 'Iphone 12', description: 'Apple cell phone', price: '199.00', slug: iphone-12, created_at: '2021-05-03T20:21:21.000000Z', updated_at: null }
            tags:
                - Endpoints
            security: []
        parameters:
            -
                in: path
                name: name
                description: ''
                example: voluptas
                required: true
                schema:
                    type: string
    /api/cart:
        get:
            summary: 'Display a items from the user cart.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                401:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    message: Unauthenticated.
                                properties:
                                    message: { type: string, example: Unauthenticated. }
            tags:
                - Endpoints
            security: []
        post:
            summary: 'Store a newly created resource in storage.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
            security: []
    /api/logout:
        get:
            summary: 'Log out .'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                401:
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    message: Unauthenticated.
                                properties:
                                    message: { type: string, example: Unauthenticated. }
            tags:
                - Endpoints
